from __future__ import annotations

import json
from pathlib import Path

from jinja2 import Template

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MCPwn Security Report - {{ target }}</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; padding: 40px; }
.container { max-width: 1200px; margin: 0 auto; }
h1 { color: #58a6ff; margin-bottom: 8px; font-size: 2em; }
h2 { color: #f0f6fc; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #30363d; }
h3 { color: #f0f6fc; margin: 16px 0 8px; }
.header { margin-bottom: 32px; padding: 24px; background: #161b22; border-radius: 8px; border: 1px solid #30363d; }
.header p { color: #8b949e; margin-top: 8px; }
.header .summary { display: flex; gap: 16px; margin-top: 16px; }
.summary-item { padding: 16px 24px; border-radius: 6px; text-align: center; min-width: 100px; }
.summary-item .count { font-size: 2em; font-weight: bold; }
.summary-item .label { font-size: 0.85em; color: #8b949e; margin-top: 4px; }
.critical { background: #3d1111; border: 1px solid #da3633; }
.critical .count { color: #ff7b72; }
.high { background: #3d1f00; border: 1px solid #d29922; }
.high .count { color: #d29922; }
.medium { background: #1f3a3d; border: 1px solid #58a6ff; }
.medium .count { color: #58a6ff; }
.low { background: #1f2a1f; border: 1px solid #3fb950; }
.low .count { color: #3fb950; }
.finding { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 20px; margin-bottom: 16px; }
.finding-header { display: flex; justify-content: space-between; align-items: start; margin-bottom: 12px; }
.finding-title { font-size: 1.1em; font-weight: 600; }
.badge { padding: 4px 10px; border-radius: 12px; font-size: 0.8em; font-weight: 500; text-transform: uppercase; }
.badge-critical { background: #da3633; color: #fff; }
.badge-high { background: #d29922; color: #000; }
.badge-medium { background: #58a6ff; color: #000; }
.badge-low { background: #3fb950; color: #000; }
.finding-meta { color: #8b949e; font-size: 0.9em; margin-bottom: 8px; }
.finding-desc { color: #c9d1d9; margin-bottom: 12px; line-height: 1.5; }
.finding-detail { background: #0d1117; border-radius: 6px; padding: 12px; font-family: 'SF Mono', monospace; font-size: 0.9em; white-space: pre-wrap; margin-bottom: 12px; color: #8b949e; }
.finding-rec { border-left: 3px solid #58a6ff; padding: 12px; background: #0d1117; border-radius: 0 6px 6px 0; color: #c9d1d9; }
.finding-rec strong { color: #58a6ff; }
.empty-state { text-align: center; padding: 64px; color: #8b949e; }
.empty-state .icon { font-size: 4em; margin-bottom: 16px; }
.evidence { margin-top: 12px; background: #0d1117; border-radius: 6px; padding: 12px; }
.evidence summary { cursor: pointer; color: #58a6ff; font-size: 0.9em; }
.evidence pre { margin-top: 8px; font-size: 0.85em; color: #8b949e; white-space: pre-wrap; }
footer { text-align: center; color: #484f58; margin-top: 48px; padding: 24px; font-size: 0.85em; }
</style>
</head>
<body>
<div class="container">
<div class="header">
<h1>MCPwn Security Report</h1>
<p>Target: <strong>{{ target }}</strong></p>
<p>Generated: {{ date }}</p>
<div class="summary">
<div class="summary-item critical"><div class="count">{{ summary.critical }}</div><div class="label">Critical</div></div>
<div class="summary-item high"><div class="count">{{ summary.high }}</div><div class="label">High</div></div>
<div class="summary-item medium"><div class="count">{{ summary.medium }}</div><div class="label">Medium</div></div>
<div class="summary-item low"><div class="count">{{ summary.low }}</div><div class="label">Low</div></div>
</div>
</div>

{% if findings %}
<h2>Findings ({{ findings|length }})</h2>
{% for f in findings %}
<div class="finding">
<div class="finding-header">
<div class="finding-title">{{ f.title }}</div>
<span class="badge badge-{{ f.severity }}">{{ f.severity }}</span>
</div>
<div class="finding-meta">{{ f.attack_type }} &middot; {{ f.target }} &middot; {{ f.id }}</div>
<div class="finding-desc">{{ f.description }}</div>
{% if f.detail %}<div class="finding-detail">{{ f.detail }}</div>{% endif %}
<div class="finding-rec"><strong>Recommendation:</strong> {{ f.recommendation }}</div>
{% if f.evidence %}
<details class="evidence">
<summary>View evidence</summary>
<pre>{{ f.evidence | tojson(indent=2) }}</pre>
</details>
{% endif %}
</div>
{% endfor %}
{% else %}
<div class="empty-state">
<div class="icon">&#x2714;</div>
<h2>No findings</h2>
<p>The target passed all security checks.</p>
</div>
{% endif %}

<footer>Generated by MCPwn - Offensive Security Testing for MCP Protocols</footer>
</div>
</body>
</html>"""


def generate_html_report(result_dict: dict, output_path: Path):
    findings = result_dict.get("findings", [])
    summary = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for f in findings:
        sev = f.get("severity", "low")
        if sev in summary:
            summary[sev] += 1

    template = Template(HTML_TEMPLATE)
    from datetime import datetime
    html = template.render(
        target=result_dict.get("target", "unknown"),
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        findings=findings,
        summary=summary,
    )
    output_path.write_text(html)
    return output_path


def save_json(result_dict: dict, output_path: Path):
    output_path.write_text(json.dumps(result_dict, indent=2))
    return output_path